### PR TITLE
Add more bindings

### PR DESCRIPTION
**Pull request by tianxing113**
Add some new bindings:

1. RotatedTranslatedShape and RotatedTranslatedShapeSettings
2. CharacterBase and CharacterBaseSettings
3. CharacterVirtual and CharacterVirtualSettings

### CODE REVIEW

**Comment by amerkoleci** [comment]
Looks really good, good job!

Thanks

**Comment by amerkoleci** [comment]
Just wanted to let you know that I did some changes to your changes and released version 2.2.0 on nuget.

Thanks again!

**Comment by jmiskovic** [comment]
I believe the `JPH_CharacterBase_IsSupported()` should return `JPH_Bool32` instead of `bool`? The `stdbool.h` is not included so the compiler throws an error when using this in pure C project.

@tianxing113 thanks for these bindings, looking forward to trying them out.

**Comment by amerkoleci** [comment]
> `JPH_Bool32` instead of `bool`?

Fixed now (commit: https://github.com/amerkoleci/JoltPhysicsSharp/commit/b57a44d9467578efa782bc680fe530ab30a61556), thanks for spotting the issue.

**Pull request merged**
