### PR TITLE
Added various missing functions

### PR DESCRIPTION
**Pull request by skyebird189**
Hello!

In this PR I am adding various missing functions, mostly in the BodyInterface. Notably, Get and Set Position & Rotation functions, and also some shape functions.

I am still working on this PR so I am opening it as a draft.

### CODE REVIEW

**Comment by amerkoleci** [comment]
Nice, tell me when you're ready to merge it!

Thanks

**Comment by skyebird189** [comment]
I've managed to fix the compilation issues in the double precision version now, and everything seems to compile correctly.

**Comment by amerkoleci** [comment]
Thanks!

**Comment by amerkoleci** [comment]
Native builds are getting ready https://github.com/amerkoleci/JoltPhysicsSharp/actions/runs/4812535226 and tomorrow morning I'll release new nuget package, thanks for your work!

**Comment by amerkoleci** [comment]
Version **1.6.2** has been released!

**Pull request merged**
