### PR TITLE
PhysicsSettings

### PR DESCRIPTION
**Pull request by bjornbytes**

### CODE REVIEW

**Comment by amerkoleci** [comment]
Windows CI build fails, I can merge and fix it by myself if you want?

**Comment by bjornbytes** [comment]
Oh, let me try using `static_cast` for those

**Comment by bjornbytes** [comment]
Looks like that worked, but it's failing on ARM64 with a blank error now.

**Comment by amerkoleci** [comment]
I'll fix win-arm64 tomorrow morning (CEST)

**Comment by bjornbytes** [comment]
Thanks for the super fast merges!

**Comment by amerkoleci** [comment]
> Thanks for the super fast merges!

Thanks for all those PR's and using this library in your engine!

**Pull request merged**
